Landing page
bamit5/Housing_Proj pull request #3
Opened 2021-05-16 19:25 UTC by Will-Hsu

Worked on the LandingPage component to reflect the updated Homehub landing page design on Figma. The page should be responsive to mobile view as well.

2021-05-21 00:23 UTC, bamit5 requested changes
Can you review the changes i specified in the comments on the code?

2021-05-21 20:08 UTC, Will-Hsu commented on FrontEnd/src/pages/index.tsx
> +export { default } from '../components/LandingPage';
Just updated!

2021-05-21 20:09 UTC, Will-Hsu commented on FrontEnd/src/components/LandingPage/LandingPage.module.scss
> +  .title{
Noted! I will be sure to update them once we have reuseable variables!

2021-05-21 20:19 UTC, Will-Hsu commented on FrontEnd/src/components/LandingPage/LandingPage.tsx
> +const Landing: FunctionComponent = () => (
Good idea! I split the page into 3 main components: WelcomeInfo, Why-Homehub, and Landing.

2021-05-21 20:22 UTC, Will-Hsu commented
Thanks for the review! I made fixes to address your three feedback. Let me know if there are any changes to be done! 
Changes: 1. Use @components/LandingPage for consistency in the codebase. 2. Refactor the Landing Page code into 3 components to increase code readability.

2021-05-30 06:42 UTC, Will-Hsu commented
The changes have been incorporated to the master branch under a different pull request -- May 29.

2021-06-01 23:45 UTC, closed without merging